apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: influxdb-pvc
  namespace: default
  labels:
    app: influxdb

spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
