apiVersion: v1
kind: Secret
metadata:
  name: pass-secret
  namespace: default
type: Opaque
data:
  loadbalancer_ip : "MTkyLjE2OC45OS4yMjA="
  ftps_pass: "WkZDWnIyZ09lbGVuWm5wSGNVS1RBZ0MwUmVXVnd6R2FubEgycnh1aTQ="
  ssh_pass: "UVVsQkFUbHJNY3FiMFNZOWliWm1JRlRTVndRY0ZjazZ5dXNjTm5LMHpqVQ=="
  influxdb_admin_pass: "end3ZDZ5elp6SlREUHpVWTBoTHFRdWZFRW5KRjdOV3BHdHprRHZuT1E="
  influxdb_telegraf_user_pass: "ODQ4YVdGOWE3UmIyeUdjWWdmbDBGam9Vamc4bkdYbnBLZEZ4QkpJNXc="
  influxdb_grafana_user_pass: "WUplY1dBNVFhWDZKZWMzU1dhdnNUa3BYR3dHTVlxRExaalFJT1NHM1U0NA=="
  mysql_admin_pass: "QTZWdFBNQ2ptTUk0VksxVmtJaDBEQXJTTTVEU0ltb0hZU1ZVcHI3a0dUdw=="
  mysql_wordpress_user_pass: "ajVzdzFNa0dmbWtTMHFSd1JiMTQ4UFhnMWJTQ0RTUmFURDN1TFN4Z1N1bw=="
  ssh_pass: "UVVsQkFUbHJNY3FiMFNZOWliWm1JRlRTVndRY0ZjazZ5dXNjTm5LMHpqVQ=="
  wordpress_admin_pass: "SG9sOUI3VmJnOEVNdU02Q0phcUIwY3l2Yjl0b0F2RmdveFNtZFFhWQ=="
