apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana-image
        volumeMounts:
          - name: grafana-pv
            mountPath: /root/grafana/data
        imagePullPolicy: Never
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 5
        env:
          - name: IDB_GRAFANA_PASS
            valueFrom:
              secretKeyRef:
                name: pass-secret
                key: influxdb_grafana_user_pass
        ports:
        - containerPort: 3000
      volumes:
      - name: grafana-pv
        persistentVolumeClaim:
            claimName: grafana-pvc
