apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: grafana
  type: LoadBalancer
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000
