apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - name: ftps
      protocol: TCP
      port: 21
      targetPort: 21
    - name: ftps-passive0
      protocol: TCP
      port: 990
      targetPort: 990
    - name: ftps-passive1
      protocol: TCP
      port: 10090
      targetPort: 10090
    - name: ftps-passive2
      protocol: TCP
      port: 10091
      targetPort: 10091
    - name: ftps-passive3
      protocol: TCP
      port: 10092
      targetPort: 10092
    - name: ftps-passive4
      protocol: TCP
      port: 10093
      targetPort: 10093
    - name: ftps-passive5
      protocol: TCP
      port: 10094
      targetPort: 10094
    - name: ftps-passive6
      protocol: TCP
      port: 10095
      targetPort: 10095
    - name: ftps-passive7
      protocol: TCP
      port: 10096
      targetPort: 10096
    - name: ftps-passive8
      protocol: TCP
      port: 10097
      targetPort: 10097
    - name: ftps-passive9
      protocol: TCP
      port: 10098
      targetPort: 10098
    - name: ftps-passive10
      protocol: TCP
      port: 10099
      targetPort: 10099
    - name: ftps-passive11
      protocol: TCP
      port: 10100
      targetPort: 10100
