apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress-image
        imagePullPolicy: Never
        env:
          - name: LB_IP
            valueFrom:
              secretKeyRef:
                name: pass-secret
                key: loadbalancer_ip
          - name: MYSQL_WP_USERPASS
            valueFrom:
              secretKeyRef:
                name: pass-secret
                key: mysql_wordpress_user_pass
          - name: WP_ADMINPASS
            valueFrom:
              secretKeyRef:
                name: pass-secret
                key: wordpress_admin_pass
        ports:
        - containerPort: 5050

