apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql-image
        imagePullPolicy: Never
        env:
          - name: MYSQL_ADMIN_PASS
            valueFrom:
              secretKeyRef:
                name: pass-secret
                key: mysql_admin_pass
          - name: MYSQL_WP_USERPASS
            valueFrom:
              secretKeyRef:
                name: pass-secret
                key: mysql_wordpress_user_pass
        livenessProbe:
          exec:
            command:
            - service
            - mariadb
            - status
          initialDelaySeconds: 20
          periodSeconds: 5
        volumeMounts:
          - name: mysql-pv
            mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: mysql-pvc
