# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    ftps.yaml                                          :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rpichon <rpichon@student.42lyon.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/07 23:19:58 by atrouill          #+#    #+#              #
#    Updated: 2021/01/25 15:48:10 by rpichon          ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-image
        imagePullPolicy: Never
        env:
          - name: FTPS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pass-secret
                key: ftps_pass
          - name: LB_IP
            valueFrom:
              secretKeyRef:
                name: pass-secret
                key: loadbalancer_ip
        ports:
        - containerPort: 21
        - containerPort: 60000
        - containerPort: 60001
        - containerPort: 60002
        - containerPort: 60003
        - containerPort: 60004
        - containerPort: 60005
        - containerPort: 60006
        - containerPort: 60007
        - containerPort: 60008
        - containerPort: 60009
        - containerPort: 60010
