apiVersion: v1
kind: Service
metadata:
  name: svc-telegraf
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: telegraf
  type: ClusterIP
  ports:
  - name: telegraf
    port: 8125
    targetPort: 8125
  - name: health
    port: 8080
    targetPort: 8080
