apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
