# config file version
apiVersion: 1

datasources:
  # <string, required> name of the datasource. Required
  - name: InfluxDB
    # <string, required> datasource type. Required
    type: influxdb
    # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
    access: proxy
    # <int> org id. will default to orgId 1 if not specified
    orgId: 1
    # <bool> mark as default datasource. Max one per org
    isDefault: true
    # <string> url
    url: http://influxdb-svc.default.svc.cluster.local:8086
    # <string> database name, if used
    database: "metrics"
    # <bool> enable/disable basic auth
    basicAuth: true
    # <string> basic auth username
    basicAuthUser: "grafana_user"
    # <bool> enable/disable basic auth
    secureJsonData.basicAuth: true
    # <string> Deprecated, use secureJsonData.basicAuthPassword
    secureJsonData.basicAuthPassword: "${IDB_GRAFANA_PASS}"
    editable: true
