apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
      tier: nginx
  template:
    metadata:
      labels:
        app: nginx
        tier: nginx
    spec:
      containers:
      - name: nginx
        image: my-nginx
        imagePullPolicy: Never
        env:
        - name: LB_IP
          valueFrom:
            secretKeyRef:
              name: pass-secret
              key: loadbalancer_ip
        - name: SSH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pass-secret
              key: ssh_pass
        - name: WPPORT
          valueFrom:
            secretKeyRef:
              name: pass-secret
              key: wordpress_port
        livenessProbe:
          exec:
            command:
              - bin/sh
              - /livenessprobe.sh
          initialDelaySeconds: 30
          periodSeconds: 5
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
